import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider } from "@/components/sidebar-context";
import { Sidebar } from "@/components/ui/app-sidebar";
import { Header } from "@/components/ui/app-header";
import TanStackProviders from "@/components/tanstack-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
//https://readdy.link/preview/89783d30-423e-4057-bd5a-3e63af7a3b71/1041448

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased  `} >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TanStackProviders>
            {children}
          </TanStackProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
